id: P000733
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4050
  title: བསྐང་བ་རྩ་གསུམ་དགྱེས་པའི་མཆོད་སྤྲིན།
  author: ''
  volumes:
    883acd7bdb7841ae81598598896afb23:
      image_group_id: I3CN4235
      title: ''
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
