id: P000733
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:39:35.440273
source_metadata:
  id: bdr:W3CN4050
  title: བསྐང་བ་རྩ་གསུམ་དགྱེས་པའི་མཆོད་སྤྲིན།
  author: ''
  volumes:
    883acd7bdb7841ae81598598896afb23:
      image_group_id: I3CN4235
      title: ''
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
